# the Foodmart XML/A data source

enabled=false

XMLA_URL=http://localhost:8080/klexserver/xmla
XMLA_DATASOURCE=Provider=Mondrian;DataSource=JRS
XMLA_CATALOG=Foodmart
XMLA_USER=klexadmin|organization_1
XMLA_PASSWORD=klexadmin
