net.sf.klexreports.extension.registry.factory.charts=net.sf.klexreports.charts.ChartsExtensionsRegistryFactory

net.sf.klexreports.extension.registry.factory.jackson.mapping=net.sf.klexreports.jackson.util.JacksonMappingExtensionsRegistryFactory
net.sf.klexreports.extension.jackson.mapping.chart=net.sf.klexreports.charts.JRChart
