net.sf.klexreports.extension.registry.factory.http.data=net.sf.klexreports.dataadapters.http.HttpDataExtensionsRegistryFactory

net.sf.klexreports.extension.registry.factory.jackson.mapping=net.sf.klexreports.jackson.util.JacksonMappingExtensionsRegistryFactory
net.sf.klexreports.extension.jackson.mapping.httpDataLocation=net.sf.klexreports.data.http.StandardHttpDataLocation
