# Generated by Django 6.0.2 on 2026-03-28 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_is_super_admin'),
        ('repos', '0002_alter_repo_path_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('report_name', models.CharField(max_length=255)),
                ('latest_commit', models.CharField(blank=True, max_length=40, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='repos.repo')),
            ],
            options={
                'db_table': 'reports',
                'unique_together': {('repo', 'path')},
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='queued', max_length=20)),
                ('output_format', models.CharField(default='pdf', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output_location', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.report')),
            ],
            options={
                'db_table': 'executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag_id', models.CharField(max_length=255, unique=True)),
                ('schedule_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='running', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('department', models.CharField(default='General', max_length=100)),
                ('cron_expression', models.CharField(blank=True, default='', max_length=255)),
                ('frequency_label', models.CharField(blank=True, default='', max_length=100)),
                ('machine_name', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_runtime_min', models.FloatField(blank=True, null=True)),
                ('max_runtime_min', models.FloatField(blank=True, default=30, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('termination_description', models.CharField(blank=True, default='', max_length=500)),
                ('exit_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_jobs', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_jobs', to='reports.report')),
            ],
            options={
                'db_table': 'scheduled_jobs',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_comments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.scheduledjob')),
            ],
            options={
                'db_table': 'job_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=True)),
                ('can_schedule', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to='accounts.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_permissions', to='reports.report')),
            ],
            options={
                'db_table': 'organization_report_permissions',
                'indexes': [models.Index(fields=['organization'], name='idx_org_report_perm_org'), models.Index(fields=['report'], name='idx_org_report_perm_report')],
                'unique_together': {('organization', 'report')},
            },
        ),
        migrations.CreateModel(
            name='ReportExecutionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dag_id', models.CharField(max_length=255)),
                ('dedupe_key', models.CharField(db_index=True, help_text='Deterministic key computed from dag_id + report + schedule window.', max_length=512)),
                ('airflow_run_id', models.CharField(blank=True, help_text='The dag_run_id sent to (or received from) Airflow.', max_length=255, null=True)),
                ('schedule_time', models.DateTimeField(blank=True, help_text='The logical schedule time this run represents.', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=20)),
                ('workload_class', models.CharField(choices=[('INTERACTIVE', 'Interactive'), ('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('HEAVY', 'Heavy')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('WAITING', 'Waiting'), ('ADMITTED', 'Admitted'), ('TRIGGERED', 'Triggered'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED_RETRYABLE', 'Failed (Retryable)'), ('FAILED_FINAL', 'Failed (Final)'), ('SKIPPED', 'Skipped'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=30)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Airflow DAG run conf / report parameters.')),
                ('overlap_policy', models.CharField(choices=[('QUEUE_ALL', 'Queue All'), ('SKIP_IF_RUNNING', 'Skip If Running'), ('LATEST_ONLY', 'Latest Only'), ('COALESCE', 'Coalesce')], default='QUEUE_ALL', max_length=30)),
                ('expected_runtime_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_error_type', models.CharField(blank=True, default='', max_length=255)),
                ('attempt_metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary debug data per attempt (timing, request IDs, …).')),
                ('expiry_time', models.DateTimeField(blank=True, help_text='If set, job is considered stale after this time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_jobs', to='accounts.organization')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_jobs', to='reports.report')),
            ],
            options={
                'db_table': 'report_execution_jobs',
                'ordering': ['priority', 'requested_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='idx_rej_status_pri'), models.Index(fields=['dag_id', 'status'], name='idx_rej_dag_status'), models.Index(fields=['dedupe_key'], name='idx_rej_dedupe'), models.Index(fields=['created_by', 'status'], name='idx_rej_user_status'), models.Index(fields=['organization', 'status'], name='idx_rej_org_status')],
            },
        ),
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=True)),
                ('can_schedule', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_permissions',
                'indexes': [models.Index(fields=['user'], name='idx_report_permissions_user'), models.Index(fields=['report'], name='idx_report_permissions_report')],
                'unique_together': {('user', 'report')},
            },
        ),
    ]
