# Generated by Django 6.0.2 on 2026-04-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjob',
            name='created_on_engine',
            field=models.CharField(choices=[('quartz', 'Quartz'), ('airflow', 'Airflow')], default='quartz', help_text='Scheduling engine that originally created this job.', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='schedule_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Full schedule configuration — enough to recreate this job on any engine.'),
        ),
    ]
