# Generated by Django 6.0.2 on 2026-04-29 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_super_admin'),
        ('reports', '0002_add_schedule_migration_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='violet', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='reports.reportgroup')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='reports.report')),
            ],
            options={
                'db_table': 'report_group_members',
            },
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='groups', through='reports.ReportGroupMember', to='reports.report'),
        ),
        migrations.CreateModel(
            name='GroupUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=True)),
                ('can_schedule', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='reports.reportgroup')),
            ],
            options={
                'db_table': 'group_user_permissions',
                'indexes': [models.Index(fields=['group'], name='idx_gup_group'), models.Index(fields=['user'], name='idx_gup_user')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupOrganizationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=True)),
                ('can_schedule', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='accounts.organization')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_permissions', to='reports.reportgroup')),
            ],
            options={
                'db_table': 'group_organization_permissions',
                'indexes': [models.Index(fields=['group'], name='idx_gop_group'), models.Index(fields=['organization'], name='idx_gop_org')],
                'unique_together': {('group', 'organization')},
            },
        ),
        migrations.AddIndex(
            model_name='reportgroupmember',
            index=models.Index(fields=['group'], name='idx_rgm_group'),
        ),
        migrations.AddIndex(
            model_name='reportgroupmember',
            index=models.Index(fields=['report'], name='idx_rgm_report'),
        ),
        migrations.AlterUniqueTogether(
            name='reportgroupmember',
            unique_together={('group', 'report')},
        ),
    ]
