# Generated by Django 6.0.2 on 2026-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportgroup_reportgroupmember_reportgroup_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='metadata_cache',
            field=models.JSONField(blank=True, default=dict, help_text='Compact metadata summary for chatbot/search. Populated from Java MetadataService.'),
        ),
        migrations.AddField(
            model_name='report',
            name='metadata_cached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
