net.sf.klexreports.extension.registry.factory.jr.statistics=net.sf.klexreports.spring.SpringExtensionsRegistryFactory
net.sf.klexreports.extension.jr.statistics.spring.beans.resource=net/sf/klexreports/ohloh/beans.xml
