#net.sf.klexreports.chart.render.type=svg
net.sf.klexreports.image.dpi=150

#only one of those below can be uncommented at a time:
net.sf.klexreports.chart.theme=eye.candy.sixties
#net.sf.klexreports.chart.theme=aegean
#net.sf.klexreports.chart.theme=default
#net.sf.klexreports.chart.theme=default.spring

#net.sf.klexreports.chart.theme=xml.simple
#net.sf.klexreports.chart.theme=xml.eye.candy.sixties
#net.sf.klexreports.chart.theme=xml.aegean
