# Generated by Django 6.0.2 on 2026-02-09 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAdapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adapter_type', models.CharField(choices=[('jdbc', 'JDBC (PostgreSQL)'), ('csv', 'CSV File'), ('mock', 'Mock Data')], max_length=20)),
                ('connection_details', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_adapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_adapters',
            },
        ),
    ]
