# Generated by Django 6.0.2 on 2026-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataadapter',
            name='adapter_type',
            field=models.CharField(choices=[('jdbc', 'JDBC (PostgreSQL)'), ('csv', 'CSV File'), ('json', 'JSON File'), ('xml', 'XML File'), ('inmemory', 'In-Memory'), ('mock', 'Mock Data')], max_length=20),
        ),
    ]
