net.sf.klexreports.extension.registry.factory.chart.theme=net.sf.klexreports.spring.SpringExtensionsRegistryFactory
net.sf.klexreports.extension.chart.theme.spring.beans.resource=net/sf/klexreports/chartthemes/spring/beans/chartThemesBeans.xml
