<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>net.sf.klexreports</groupId>
		<artifactId>klexreports-ext-parent</artifactId>
		<version>${revision}</version>
		<relativePath>../pom-parent.xml</relativePath>
	</parent>
	<artifactId>klexreports-json</artifactId>
	<packaging>jar</packaging>
	<name>KlexReports JSON</name>
	<description>KlexReports JSON</description>
	<url>http://klexreports.sourceforge.net</url>
	<scm>
		<connection>${scmConnection}</connection>
		<tag>${revision}</tag>
		<url>${scmUrl}</url>
	</scm>
	<dependencies>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>${commons-logging.version}</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>${jackson.version}</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>${jackson.version}</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
		<dependency>
			<groupId>antlr</groupId>
			<artifactId>antlr</artifactId>
			<version>${antlr.version}</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>${exec-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>antlr</id>
						<configuration>
							<mainClass>antlr.Tool</mainClass>
							<arguments>
								<argument>-o</argument>
								<argument>src/main/java/net/sf/klexreports/engine/json/parser/</argument>
								<argument>src/main/antlr/net/sf/klexreports/engine/json/parser/json_grammar.g</argument>
							</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
