#net.sf.klexreports.extension.registry.factory.sort=net.sf.klexreports.components.sort.SortParameterContributorExtensionFactory
net.sf.klexreports.extension.registry.factory.sort=net.sf.klexreports.components.sort.SortComponentExtensionsRegistryFactory
