# Generated by Django 6.0.2 on 2026-02-09 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('path_prefix', models.CharField(default='reports', max_length=255)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('git_remote_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repos',
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
