# Generated by Django 6.0.2 on 2026-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='path_prefix',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
