net.sf.klexreports.extension.registry.factory.default=net.sf.klexreports.extensions.DefaultExtensionsRegistryFactory
net.sf.klexreports.extension.registry.factory.governor=net.sf.klexreports.governors.GovernorExtensionsRegistryFactory

net.sf.klexreports.extension.registry.factory.components=net.sf.klexreports.components.ComponentsExtensionsRegistryFactory
net.sf.klexreports.extension.registry.factory.parts=net.sf.klexreports.parts.PartComponentsExtensionsRegistryFactory

net.sf.klexreports.extension.registry.factory.sql.clause.functions=net.sf.klexreports.engine.query.SQLQueryClauseFunctionsExtensions
net.sf.klexreports.extension.registry.factory.date.range.clause.functions=net.sf.klexreports.types.date.DateRangeQueryClauseExtensions

net.sf.klexreports.extension.registry.factory.repository=net.sf.klexreports.repo.DefaultRepositoryExtensionsRegistryFactory
net.sf.klexreports.extension.registry.factory.property.style.provider=net.sf.klexreports.engine.style.PropertyStyleProviderExtensionFactory

net.sf.klexreports.extension.registry.factory.content.type.mapping=net.sf.klexreports.web.util.ContentTypeMappingExtensionsRegistryFactory
net.sf.klexreports.extension.content.type.mapping.js=text/javascript; charset=UTF-8
net.sf.klexreports.extension.content.type.mapping.css=text/css
net.sf.klexreports.extension.content.type.mapping.eot=application/vnd.ms-fontobject
net.sf.klexreports.extension.content.type.mapping.svg=image/svg+xml
net.sf.klexreports.extension.content.type.mapping.ttf=font/ttf
net.sf.klexreports.extension.content.type.mapping.woff=font/woff
net.sf.klexreports.extension.content.type.mapping.png=image/png
net.sf.klexreports.extension.content.type.mapping.gif=image/gif
net.sf.klexreports.extension.content.type.mapping.tmpl=text/plain

net.sf.klexreports.extension.registry.factory.simple.font.families=net.sf.klexreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.klexreports.extension.simple.font.families.icons=net/sf/klexreports/fonts/icons/klexreports-fonts.xml

net.sf.klexreports.extension.registry.factory.matcher.exporter.filter.mapping=net.sf.klexreports.engine.export.MatcherExportFilterMappingExtensionsRegistryFactory
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.html.includes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.html.excludes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.pdf.includes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.pdf.excludes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.graphics2d.includes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.graphics2d.excludes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.docx.includes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.docx.excludes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.xlsx.includes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.xlsx.excludes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.pptx.includes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.pptx.excludes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.xls.includes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.xls.excludes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.rtf.includes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.rtf.excludes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.odt.includes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.odt.excludes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.ods.includes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.ods.excludes=net.sf.klexreports.components.table.header.icon.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.csv.includes=net.sf.klexreports.components.table.header.label
net.sf.klexreports.extension.matcher.export.filter.net.sf.klexreports.csv.excludes=net.sf.klexreports.components.table.header.icon.label
