net.sf.klexreports.extension.registry.factory.functions=net.sf.klexreports.functions.FunctionsRegistryFactory
net.sf.klexreports.extension.functions.datetime=net.sf.klexreports.functions.standard.DateTimeFunctions
net.sf.klexreports.extension.functions.math=net.sf.klexreports.functions.standard.MathFunctions, net.sf.klexreports.functions.standard.LogicalFunctions
net.sf.klexreports.extension.functions.text=net.sf.klexreports.functions.standard.TextFunctions 
net.sf.klexreports.extension.functions.report=net.sf.klexreports.functions.standard.ReportFunctions 

