<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>net.sf.klexreports</groupId>
		<artifactId>klexreports-ext-parent</artifactId>
		<version>${revision}</version>
		<relativePath>../pom-parent.xml</relativePath>
	</parent>
	<artifactId>klexreports-ejbql</artifactId>
	<packaging>jar</packaging>
	<name>KlexReports EJBQL Jakarta EE</name>
	<description>KlexReports EJBQL Jakarta EE</description>
	<url>http://klexreports.sourceforge.net</url>
	<scm>
		<connection>${scmConnection}</connection>
		<tag>${revision}</tag>
		<url>${scmUrl}</url>
	</scm>
	<dependencies>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>${commons-logging.version}</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
			<version>${jakarta.persistence-api.version}</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
		<dependency>
			<groupId>net.sf.klexreports</groupId>
			<artifactId>klexreports-data-adapters</artifactId>
			<version>${revision}</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
	</dependencies>
</project>
