# Locations of font files can be specified.
# As the PDF font name you can use the font name or the suffix of the key (e.g. Sans.Slanted).
net.sf.klexreports.export.pdf.font.Sans.Bold=../../../ext/fonts/src/main/resources/net/sf/klexreports/fonts/dejavu/DejaVuSans-Bold.ttf
net.sf.klexreports.export.pdf.font.Sans.Slanted=../../../ext/fonts/src/main/resources/net/sf/klexreports/fonts/dejavu/DejaVuSans-Oblique.ttf

# Also font directories can be specified.
# net.sf.klexreports.export.pdf.fontdir.klex=../../../ext/fonts/src/main/resources/net/sf/klexreports/fonts/dejavu
